name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make deploy
    - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u y2khub --password-stdin
    - run: docker push y2khub/minesweeper
